apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e2e-test-1776049890170-gitops
  description: This is GitOps manifest for e2e-test-1776049890170   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=e2e-test-1776049890170
    backstage.io/kubernetes-id: e2e-test-1776049890170 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: xjiangorg/e2e-test-1776049890170-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:e2e-test-1776049890170
