apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-test-1776049890170
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/test-image:github-68d7bafd2a5d5661f908f9efc26823bec0e9e2c7
          name: container-image
