apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e2e-test-1776049890170
  janus-idp.io/tekton: e2e-test-1776049890170
  backstage.io/kubernetes-id: e2e-test-1776049890170
  backstage.io/kubernetes-namespace: tssc-app-deployment 
  app.kubernetes.io/part-of: e2e-test-1776049890170
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
